# Generated by Django 2.0 on 2020-07-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(default='customer', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=12)),
                ('mobile_no', models.CharField(max_length=12)),
                ('category', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=400, null=True)),
                ('openhours', models.CharField(max_length=30, null=True)),
                ('latitude', models.CharField(max_length=30, null=True)),
                ('longitude', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
