# Generated by Django 2.0 on 2020-07-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shopname',
            field=models.CharField(default='customer', max_length=30, null=True),
        ),
    ]
