# Generated by Django 2.0 on 2020-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200725_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
